  
# stage 1
FROM node:alpine as node
WORKDIR /app
COPY package*.json ./
COPY . .
RUN npm install
RUN npm run build --prod

# stage 2
FROM nginx:alpine
COPY  .htaccess /app/dist/ClientPizzaProj
COPY --from=node /app/dist/ClientPizzaProj /usr/share/nginx/html
COPY ./nginx.conf /etc/nginx/conf.d/default.conf

CMD sed -i -e 's/$PORT/'"$PORT"'/g' /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'